version: 2.1

orbs:
  slack: circleci/slack@4.1.4

executors:
  node:
    docker:
      - image: circleci/node:12
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - save_modules
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  build_and_test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: unit test
          command: yarn test
  deploy:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: deploy
          command: chmod +x deploy.sh && ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_and_test
      - deploy:
          requires:
           - build_and_test
          filters:
            branches:
              only:
                - main    
       